apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: default
  labels:
    app.kubernetes.io/name: it-tools
    app: it-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: it-tools
  template:
    metadata:
      labels:
        app.kubernetes.io/name: it-tools
    spec:
      containers:
      - image: corentinth/it-tools:latest
        name: it-tools
        ports:
        - containerPort: 80
