apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-volume-claim
  namespace: portainer
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
