---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: 1password
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: connect
  namespace: default
spec:
  chart:
    spec:
      chart: connect
      version: '1.15.*'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
  interval: 5h
