apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-ingress
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.1
    helm:
      releaseName: quickstart
      parameters:
        - name: "nginx-ingress.controller.service.annotations.metallb\\.universe\\.tf/loadBalancerIPs"
          value: 192.168.1.252
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
