---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: quickstart
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: '4.0.*'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 5h
  values:
    controller:
      service:
        annotations:
          "metallb.universe.tf/loadBalancerIPs": "192.168.1.252"
      config:
        use-proxy-protocol: "true"


