apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-config-volume-claim
  namespace: default
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10M
