apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy-deployment
  namespace: default
  labels:
    app.kubernetes.io/name: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dashy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dashy
    spec:
      containers:
        - image: lissy93/dashy
          name: dashy
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pvc
              mountPath: /app/public
              readOnly: false
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: dashy-volume
