apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.201
  name: dashy-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: dashy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
